In [126]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [127]:
data = pd.read_csv('student-mat.csv',sep=';') # student-mat.csv

In [128]:
data

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [129]:
data = data.drop_duplicates()
data

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [130]:
data.isnull().sum() # No Null Values here

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [131]:
data.dropna(how='any')

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [132]:
data.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177   
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430   
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  395.000000  395.000000  395.000000  395.000000  
mean     5.708861   10.908861   10.713924   10.415190  
std      8.003096    3.319195    3.761505    4.581443  
min      0.000000    3.000000    0.000000    0.000000  
25%      0.000000    8.000000    9.000000    8.000000  
50%      4.000000   11.000000   11.000000   11.000000  
75%      8.000000   13.000000   13.000000   14.000000  
max     75.000000   19.000000   19.000000   20.000000

In [133]:
x = data.iloc[:,:32]
y = data['G3'].values
x.shape
x

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... romantic famrel  freetime  goout  Dalc Walc health absences  G1  G2  
0    ...       no      4         3      4     1    1      3        6   5   6  
1    ...       no      5         3      3     1    1      3        4   5   5  
2    ...       no      4         3      2     2    3      3       10   7   8  
3    ...      yes      3         2      2     1    1      5        2  15  14  
4    ...       no      4         3      2     1    2      5        4   6  10  
..   ...      ...    ...       ...    ...   ...  ...    ...      ...  ..  ..  
390  ...       no      5         5      4     4    5      4       11   9   9  
391  ...       no      2         4      5     3    4      2        3  14  16  
392  ...       no      5         5      3     3    3      3        3  10   8  
393  ...       no      4         4      1     3    4      5        0  11  12  
394  ...       no      3         2      3     3    3      5        5   8   9  

[395 rows x 32 columns]

In [134]:
y

array([ 6,  6, 10, 15, 10, 15, 11,  6, 19, 15,  9, 12, 14, 11, 16, 14, 14,
       10,  5, 10, 15, 15, 16, 12,  8,  8, 11, 15, 11, 11, 12, 17, 16, 12,
       15,  6, 18, 15, 11, 13, 11, 12, 18, 11,  9,  6, 11, 20, 14,  7, 13,
       13, 10, 11, 13, 10, 15, 15,  9, 16, 11, 11,  9,  9, 10, 15, 12,  6,
        8, 16, 15, 10,  5, 14, 11, 10, 10, 11, 10,  5, 12, 11,  6, 15, 10,
        8,  6, 14, 10,  7,  8, 18,  6, 10, 14, 10, 15, 10, 14,  8,  5, 17,
       14,  6, 18, 11,  8, 18, 13, 16, 19, 10, 13, 19,  9, 16, 14, 13,  8,
       13, 15, 15, 13, 13,  8, 12, 11,  9,  0, 18,  0,  0, 12, 11,  0,  0,
        0,  0, 12, 15,  0,  9, 11, 13,  0, 11,  0, 11,  0, 10,  0, 14, 10,
        0, 12,  8, 13, 10, 15, 12,  0,  7,  0, 10,  7, 12, 10, 16,  0, 14,
        0, 16, 10,  0,  9,  9, 11,  6,  9, 11,  8, 12, 17,  8, 12, 11, 11,
       15,  9, 10, 13,  9,  8, 10, 14, 15, 16, 10, 18, 10, 16, 10, 10,  6,
       11,  9,  7, 13, 10,  7,  8, 13, 14,  8, 10, 15,  4,  8,  8, 10,  6,
        0, 17, 13, 14,  7

In [135]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0,1,3,4,5,8,9,10,11,15,16,17,18,19,20,21,22])], remainder='passthrough')
print(ct)
x = np.array(ct.fit_transform(x))

ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
                  transformer_weights=None,
                  transformers=[('encoder',
                                 OneHotEncoder(categories='auto', drop=None,
                                               dtype=<class 'numpy.float64'>,
                                               handle_unknown='error',
                                               sparse=True),
                                 [0, 1, 3, 4, 5, 8, 9, 10, 11, 15, 16, 17, 18,
                                  19, 20, 21, 22])],
                  verbose=False)


In [136]:
x

array([[ 1.,  0.,  1., ...,  6.,  5.,  6.],
       [ 1.,  0.,  1., ...,  4.,  5.,  5.],
       [ 1.,  0.,  1., ..., 10.,  7.,  8.],
       ...,
       [ 0.,  1.,  0., ...,  3., 10.,  8.],
       [ 0.,  1.,  0., ...,  0., 11., 12.],
       [ 0.,  1.,  0., ...,  5.,  8.,  9.]])

In [137]:
y = LabelEncoder().fit_transform(y)

In [138]:
y

array([ 3,  3,  7, 12,  7, 12,  8,  3, 16, 12,  6,  9, 11,  8, 13, 11, 11,
        7,  2,  7, 12, 12, 13,  9,  5,  5,  8, 12,  8,  8,  9, 14, 13,  9,
       12,  3, 15, 12,  8, 10,  8,  9, 15,  8,  6,  3,  8, 17, 11,  4, 10,
       10,  7,  8, 10,  7, 12, 12,  6, 13,  8,  8,  6,  6,  7, 12,  9,  3,
        5, 13, 12,  7,  2, 11,  8,  7,  7,  8,  7,  2,  9,  8,  3, 12,  7,
        5,  3, 11,  7,  4,  5, 15,  3,  7, 11,  7, 12,  7, 11,  5,  2, 14,
       11,  3, 15,  8,  5, 15, 10, 13, 16,  7, 10, 16,  6, 13, 11, 10,  5,
       10, 12, 12, 10, 10,  5,  9,  8,  6,  0, 15,  0,  0,  9,  8,  0,  0,
        0,  0,  9, 12,  0,  6,  8, 10,  0,  8,  0,  8,  0,  7,  0, 11,  7,
        0,  9,  5, 10,  7, 12,  9,  0,  4,  0,  7,  4,  9,  7, 13,  0, 11,
        0, 13,  7,  0,  6,  6,  8,  3,  6,  8,  5,  9, 14,  5,  9,  8,  8,
       12,  6,  7, 10,  6,  5,  7, 11, 12, 13,  7, 15,  7, 13,  7,  7,  3,
        8,  6,  4, 10,  7,  4,  5, 10, 11,  5,  7, 12,  1,  5,  5,  7,  3,
        0, 14, 10, 11,  4

In [139]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=2)

In [140]:
x_train.shape

(316, 58)

In [141]:
x_test.shape

(79, 58)

In [142]:
y_train.shape

(316,)

In [143]:
y_test.shape

(79,)

In [147]:
stObj = StandardScaler()
x_train = stObj.fit_transform(x_train)
x_test = stObj.fit_transform(x_test)

array([[ 0.35856858, -0.35856858, -1.09290642, ...,  0.19992068,
         0.05781216,  0.66339097],
       [ 0.35856858, -0.35856858, -1.09290642, ..., -0.92820317,
         1.88467646,  1.53202999],
       [ 0.35856858, -0.35856858,  0.91499142, ..., -0.55216188,
         1.58019907,  1.53202999],
       ...,
       [ 0.35856858, -0.35856858,  0.91499142, ..., -0.55216188,
        -1.46457475, -1.36343338],
       [ 0.35856858, -0.35856858,  0.91499142, ..., -0.55216188,
         1.58019907,  1.24248365],
       [-2.78886676,  2.78886676,  0.91499142, ...,  0.57596197,
         0.66676693,  0.0842983 ]])